
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run PyTests on Code

on:
  push:
    branches: [ "dev","main" ]
  pull_request:
    branches: [ "dev","main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -r code/requirements.txt
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
    - name: Install TF Object Detection API
      run: |
        git clone https://github.com/tensorflow/models.git
        cd models/research
        protoc object_detection/protos/*.proto --python_out=.
        cp object_detection/packages/tf2/setup.py .
        python -m pip install .
    - name: Create mock image files
      run: |
        mkdir -p ./StereoVision/assets 
        touch ./StereoVision/assets/braccioright.png
        
    - name: Test with pytest
      env:
        USE_MOCK: true
      run: |
        pip install pytest pytest-cov
        pytest code/ --ignore=code/archived --doctest-modules --junitxml=junit/test-results.xml --cov=code --cov-report=xml --cov-report=html

    - name: Upload HTML coverage report
      uses: actions/upload-artifact@v4
      with:
        name: htmlcov
        path: htmlcov/

    - name: Upload XML coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage.xml
        path: coverage.xml

        
